ROW1 EQU P1.0    // KET NOI HANG 1 CUA KEYPAD VOI CHAN P1.0
ROW2 EQU P1.1
ROW3 EQU P1.2
ROW4 EQU P1.3

COL1 EQU P1.4  	// KET NOI COT 1 CUA KEYPAD VOI CHAN P1.4
COL2 EQU P1.5
COL3 EQU P1.6
COL4 EQU P1.7

RS BIT P3.0
RW BIT P3.1
E  BIT P3.2

DULIEU EQU P2   		// KET VOI CHAN CUA MAN HINH LCD VOI CHAN P2
ORG 00H
CLR P3.3	

// DAT MAT KHAU MAC DINH
MOV 31H, #1
MOV 32H, #3
MOV 33H, #1
MOV 34H, #8

MOV 40H, #60H
MOV 70H, #80H
MOV R5, #00H  // GIA TRI BIEN DEM NHAP MAT KHAU SAI
CLR P3.6
CLR P3.7
ACALL LCD_INIT
MENU_2: 				// Menu HIEN THI
	MOV DPTR,#THONGTIN1
	LOOP1:
		MOV A, #00H
		MOVC A,@A+DPTR
		JZ EXIT
		ACALL LCD_WRITE
		INC DPTR
		SJMP LOOP1
	EXIT:

	MOV DPTR, #THONGTIN2
	ACALL LINE2
	LOOP2:
		MOV A, #00H
		MOVC A,@A+DPTR
		JZ EXIT1
		ACALL LCD_WRITE
		INC DPTR
		SJMP LOOP2
	EXIT1:

MENU1:
	CLR COL4
	JNB ROW1,NHAP_MK		// CHON COT 4 HANG 1 LA PHIM NHAP MAT KHAU
	JNB ROW2, STEP			// CHON COT 4 HANG 2 LA PHIM DOI MAT KHAU
	SETB COL4
	JMP MENU1	
STEP: LJMP DOI_MK 

NHAP_MK: 					// HIEN THI DONG CHU NHAP MAT KHAU
	ACALL CLEAR_SCREEN
	ACALL LCD_COMMAND
	MOV DPTR, #NHAP_PASS
	LAP1:
	MOV A, #00H
	MOVC A, @A+DPTR
	JZ DISPLAY_LINE2
	ACALL LCD_WRITE
	INC DPTR
	SJMP LAP1

DISPLAY_LINE2:
	ACALL LINE2
	
	
KEYPAD:						// LAM VIEC VOI MA TRAN BAN PHIM
	MOV P1, #11111111B 		// DE P1 LÀ MUC CAO
	CLR COL1				// DAT COT 1 VE MUC THAP SAU DO KIEM TRA TUNG HANG NEU HANG NAO BANG 1 THI MAY SE HIEU HANG PHIM DO DUOC BAM
	JNB ROW1, H1
	JNB ROW2,H2
	JNB ROW3,H3
	JNB ROW4,H4
	ACALL DELAY10MS
	SETB COL1				// DAT LAI COT 1 VE MUC CAO
	
	CLR COL2				// DAT COT 2 VE MUC THAP SAU DO KIEM TRA TUNG HANG NEU HANG NAO BANG 1 THI MAY SE HIEU HANG PHIM DO DUOC BAM
	JNB ROW1,H5
	JNB ROW2,H6
	JNB ROW3,H7
	JNB ROW4,H8
	ACALL DELAY10MS
	SETB COL2				// DAT LAI COT 2 VE MUC CAO

	CLR COL3				// DAT COT 3 VE MUC THAP SAU DO KIEM TRA TUNG HANG NEU HANG NAO BANG 1 THI MAY SE HIEU HANG PHIM DO DUOC BAM
	JNB ROW1,H9
	JNB ROW2,H10
	JNB ROW3,H11
	ACALL DELAY10MS
	SETB COL3				// DAT LAI COT 3 VE MUC CAO
	JMP KEYPAD
	
	
H1: LJMP DISPLAY_PASSWORD_7 				
H2: LJMP DISPLAY_PASSWORD_4
H3: LJMP DISPLAY_PASSWORD_1
H4: LJMP DISPLAY_ENTER
H5: LJMP DISPLAY_PASSWORD_8
H6: LJMP DISPLAY_PASSWORD_5
H7: LJMP DISPLAY_PASSWORD_2
H8: LJMP DISPLAY_PASSWORD_0
H9: LJMP DISPLAY_PASSWORD_9
H10: LJMP DISPLAY_PASSWORD_6
H11: LJMP DISPLAY_PASSWORD_3

// CHUONG TRINH CAI DAT TUNG SO CUA BAN PHIM KEYPAD

DISPLAY_PASSWORD_0:
	MOV A, #'*' 			// HIEN THI KI TU * KHI BAM VAO MOT SO
	ACALL LCD_WRITE			
	ACALL DELAY_0_1S
	MOV R1, 40H				// GAN R1 BANG 40H
	MOV @R1,#0H 			// DI CHUYEN GIA TRI 0H VAO O NHO CON TRO R1 TRO DEN 
	INC 40H					// TANG GIA TRI 
	JMP KEYPAD
DISPLAY_PASSWORD_1:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 40H
	MOV @R1,#1H
	INC 40H
	JMP KEYPAD
DISPLAY_PASSWORD_2:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 40H
	MOV @R1,#2H
	INC 40H
	JMP KEYPAD
DISPLAY_PASSWORD_3:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 40H
	MOV @R1,#3H
	INC 40H
	JMP KEYPAD
DISPLAY_PASSWORD_4:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 40H
	MOV @R1,#4H
	INC 40H
	JMP KEYPAD

DISPLAY_PASSWORD_5:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 40H
	MOV @R1,#5H
	INC 40H
	JMP KEYPAD
DISPLAY_PASSWORD_6:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 40H
	MOV @R1,#6H
	INC 40H
	JMP KEYPAD
DISPLAY_PASSWORD_7:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 40H
	MOV @R1,#7H
	INC 40H
	JMP KEYPAD
	
DISPLAY_PASSWORD_8:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 40H
	MOV @R1,#8H
	INC 40H
	JMP KEYPAD

DISPLAY_PASSWORD_9:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 40H
	MOV @R1,#9H
	INC 40H
	JMP KEYPAD

DISPLAY_ENTER: 				// PHIM ON/C DE KIEM TRA MAT KHAU

	MOV 40H, #60H  			// GAN GIA TRI 60H VAO O NHO CO DIA CHI 40H
	MOV R1, 40H				// GAN GIA TRI CUA O NHO TAI DIA CHI 40H VAO THANH GHI R1 ( DUA GIA TRI 60H VAO THANH GHI R1)
	MOV A, @R1				// GAN GIA TRI TU VUNG NHO TAI DIA CHI DUOC LUU TRU TRONG THANH GHI R1 VAO THANH GHI A  (DUA GIA TRI 60H TU VUNG NHO VAO THANH GHI A)
	CJNE A, 31H, CHECK_FAIL				// NEU GIA TRI TRONG THANH GHI A KHAC 31H THI NHAY DEN CHECK_FAIL
	INC 40H
	MOV R1, 40H
	MOV A, @R1
	CJNE A, 32H, CHECK_FAIL
	INC 40H
	MOV R1, 40H
	MOV A, @R1
	CJNE A, 33H, CHECK_FAIL
	INC 40H
	MOV R1, 40H
	MOV A, @R1
	CJNE A, 34H, CHECK_FAIL
	JMP CHECK_RIGHT 			// NEU KIEM TRA DUNG HET THI NHAY TOI HAM CHECK_RIGHT
	JMP MENU1
	ACALL MOTOR					// MOTOR QUAY


CHECK_FAIL:					
	CJNE R5, #03H, INCRESE			// NEU GIA TRI BIEN DEM KHAC 3 SE NHAY TOI HAM INCRESE
	LJMP WAIT						// NEU SAI THUC HIEN NHAY TOI WAIT 
	//ACALL CLEAR_SCREEN
	ACALL DELAY50S
	JMP MENU_2
INCRESE: INC R5						// TANG GIA TRI CUA THANH GHI R5 LEN 1
	ACALL CLEAR_SCREEN
	ACALL BUZZER					// GOI TOI HAM CÒI
	MOV DPTR, #THATBAI
LOOP3:
	MOV A, #00H
	MOVC A,@A+DPTR
	JZ EXIT3
	ACALL LCD_WRITE
	INC DPTR
	SJMP LOOP3
EXIT3:	

// CHUONG TRINH CHO CÒI
BUZZER:
	SETB P3.3
	ACALL DELAY
	CLR P3.3
	RET

//=========================================== KEYPASS FOR CHANGE
DOI_MK:					// HAM HIEN THI DOI MAT KHAU 
	ACALL CLEAR_SCREEN
	ACALL LCD_COMMAND
	MOV DPTR, #NHAP_PASS_CU
	LAP2:
	MOV A, #00H
	MOVC A, @A+DPTR
	JZ EXIT4
	ACALL LCD_WRITE
	INC DPTR
	SJMP LAP2
EXIT4:

NHAP_PASS_CU_1: 
	ACALL LINE2
	ACALL KEYPAD1
	
WAIT: 					// ham hien thi khoa trong 50s
	ACALL DELAY10MS
	ACALL CLEAR_SCREEN
	MOV DPTR, #CHO50S
LOOP9:
	MOV A, #00H
	MOVC A,@A+DPTR
	JZ EXIT9
	ACALL LCD_WRITE
	INC DPTR
	SJMP LOOP9
EXIT9: LJMP DELAY50S

// ham quet ma tran ban phim voi muc dich doi mat khau
KEYPAD1:	
	MOV P1, #11111111B 				// DAT P1 O MUC CAO
	CLR COL1						// DAT COT 1 VE MUC THAP
	JNB ROW1, D1					// KIEM TRA TUNG HANG NEU HANG NAO BANG 1 SE DUOC HIEU LA BAM PHIM DO
	JNB ROW2,D2
	JNB ROW3,D3
	ACALL DELAY10MS
	SETB COL1						// DAT LAI COT 1 O MUC CAO
	
	CLR COL2						// DAT COT 2 O MUC THAP
	JNB ROW1,D5						// KIEM TRA TUNG HANG NEU HANG NAO BANG 1 SE DUOC HIEU LA BAM PHIM DO
	JNB ROW2,D6
	JNB ROW3,D7
	JNB ROW4,D8
	ACALL DELAY10MS
	SETB COL2						// DAT LAI COT 2 O MUC CAO

	CLR COL3						// DAT COT 3 O MUC THAP
	JNB ROW1,D9						// KIEM TRA TUNG HANG NEU HANG NAO BANG 1 SE DUOC HIEU LA BAM PHIM DO
	JNB ROW2,D10
	JNB ROW3,D11
	JNB ROW4,D12
	ACALL DELAY10MS
	SETB COL3						// DAT LAI COT 3 O MUC CAO
	
	CLR COL4						// DAT COT 4 O MUC THAP
	JNB ROW4, D13					// KIEM TRA TUNG HANG NEU HANG NAO BANG 1 SE DUOC HIEU LA BAM PHIM DO
	JNB ROW3, D14
	SETB COL4
	ACALL DELAY10MS
	JMP KEYPAD1
	
D1: LJMP PASSWORD_7 
D2: LJMP PASSWORD_4
D3: LJMP PASSWORD_1
D5: LJMP PASSWORD_8
D6: LJMP PASSWORD_5
D7: LJMP PASSWORD_2
D8: LJMP PASSWORD_0
D9: LJMP PASSWORD_9
D10: LJMP PASSWORD_6
D11: LJMP PASSWORD_3
D12: LJMP DISPLAY_OLD_PASS    		// PHIM = LA PHIM DOI MAT KHAU 
D13: LJMP RECHECK					// PHIM + LA PHIM NHAP MAT KHAU MOI
D14: LJMP RECHECK1					// PHIM + LA PHIM  KIEM TRA MAT KHAU MOI 

PASSWORD_0:
	MOV A, #'*'						// HIEN THI KI TU * KHI BAM VAO MOT SO
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 70H						// DI CHUYEN GIA TRI 70H VAO THANH GHI R1
	MOV @R1,#0H						// DI CHUYEN GIA TRI 0H VAO O NHO CON TRO R1 TRO DEN
	INC 70H							// TANG GIA TRI TAI DIA CHI 70H LEN 1
	JMP KEYPAD1
PASSWORD_1:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 70H
	MOV @R1,#1H
	INC 70H
	JMP KEYPAD1
PASSWORD_2:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 70H
	MOV @R1,#2H
	INC 70H
	JMP KEYPAD1
PASSWORD_3:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 70H
	MOV @R1,#3H
	INC 70H
	JMP KEYPAD1
PASSWORD_4:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 70H
	MOV @R1,#4H
	INC 70H
	JMP KEYPAD1

PASSWORD_5:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 70H
	MOV @R1,#5H
	INC 70H
	JMP KEYPAD1
PASSWORD_6:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 70H
	MOV @R1,#6H
	INC 70H
	JMP KEYPAD1
PASSWORD_7:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 70H
	MOV @R1,#7H
	INC 70H
	JMP KEYPAD1
	
PASSWORD_8:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 70H
	MOV @R1,#8H
	INC 70H
	JMP KEYPAD1

PASSWORD_9:
	MOV A, #'*'
	ACALL LCD_WRITE
	ACALL DELAY_0_1S
	MOV R1, 70H
	MOV @R1,#9H
	INC 70H
	JMP KEYPAD1
DISPLAY_OLD_PASS:	 
	ACALL CHECK_PASS

CHECK_PASS: 			// KIEM TRA MAT KHAU VOI MAT KHAU BAN DAU
	MOV 70H, #80H		// GAN GIA TRI 80H VAO O NHO CO DIA CHI 70H
	MOV R1, 70H			// GAN GIA TRI CUA O NHO TAI DIA CHI 70H VAO THANH GHI R1 ( DUA GIA TRI 80H VAO THANH GHI R1)
	MOV A, @R1			// GAN GIA TRI TU VUNG NHO TAI DIA CHI DUOC LUU TRU TRONG THANH GHI R1 VAO THANH GHI A  (DUA GIA TRI 80H TU VUNG NHO VAO THANH GHI A)
	CJNE A, 31H, WRONG			// NEU GIA TRI TRONG THANH GHI A KHAC 31H THI NHAY DEN WRONG
	
	INC 70H					// TANG GIA TRI TAI DIA CHI 70H LEN 1
	MOV R1, 70H
	MOV A, @R1
	CJNE A, 32H, WRONG
	
	INC 70H
	MOV R1, 70H
	MOV A, @R1
	CJNE A, 33H, WRONG
	
	INC 70H
	MOV R1, 70H
	MOV A, @R1
	CJNE A, 34H, WRONG
	JMP NEW_PASS			//  NEU KIEM TRA DUNG HET THI NHAY TOI HAM NEW_PASS
RECHECK:					
	ACALL RE_WRITE   // HAM NHAP LAI MAT KHAU
	
RECHECK1:			// HAM SO SANH MAT KHAU MOI VOI MAT KHAU VUA NHAP
	CLR 50H			// XOA GIA TRI TAI DIA CHI 50H 
	MOV 50H, #0A0H 		// DI CHUYEN GIA TRI 0A0H VAO O NHO TAI DIA CHI 50H
	MOV R1, 50H			// DI CHUYEN GIA TRI TAI DIA CHI 50H VAO THANH GHI R1
C1:
	CLR A				// 
	MOV A, @R1
	CJNE A, 80H, WRONG
	JMP C2
C2:
	CLR A
	INC R1
	MOV A, @R1
	CJNE A, 81H, WRONG
	JMP C3
C3:
	CLR A
	INC R1
	MOV A, @R1
	CJNE A, 82H, WRONG
	JMP C4
C4:
	CLR A
	INC R1
	MOV A, @R1
	CJNE A, 83H, WRONG
	JMP SAVE


NEW_PASS:			// HAM HIEN THI NHAP MAT KHAU MOI
	MOV 70H, #80H		// GAN GIA TRI 80H VAO O NHO CO DIA CHI 70H
	ACALL CLEAR_SCREEN
	MOV DPTR, #PASS_MOI
LOOP5:
	MOV A, #00H
	MOVC A,@A+DPTR
	JZ EXIT5
	ACALL LCD_WRITE
	INC DPTR
	SJMP LOOP5
EXIT5:
	ACALL LINE2
	ACALL KEYPAD1

WRONG:			// HAM HIEN THI KHONG DUNG KHI NHAP LAI MAT KHAU KHAC MAT KHAU VUA NHAP
	ACALL DELAY10MS
	ACALL CLEAR_SCREEN
	MOV DPTR, #SAI
LOOP7:
	MOV A, #00H
	MOVC A,@A+DPTR
	JZ EXIT7
	ACALL LCD_WRITE
	INC DPTR
	SJMP LOOP7
EXIT7:
	ACALL CLEAR_SCREEN
	JMP MENU_2
/*	
CHANGE_PASS:
	MOV 31H, 080H
	MOV 32H, 081H
	MOV 33H, 082H
	MOV 34H, 083H
	ACALL CLEAR_SCREEN
	ACALL SAVE
*/
SAVE:				// HAM HIEN THI LUU THANH CONG KHI SO SANH MAT KHAU NHAP LAI VA MAT KHAU VUA NHAP GIONG NHAU
	ACALL CLEAR_SCREEN
	MOV DPTR, #SAVE_SUCCESS
		LOOP4:
		MOV A, #00H
		MOVC A,@A+DPTR
		JZ EXIT6
		ACALL LCD_WRITE
		INC DPTR
		SJMP LOOP4
		ACALL DELAY
EXIT6:

RE_WRITE: 					// HAM HIEN THI NHAP LAI MAT KHAU
	MOV 70H, #0A0H			
	ACALL CLEAR_SCREEN
	MOV DPTR, #NHAP_LAI 
LOOP8:
	MOV A, #00H
	MOVC A,@A+DPTR
	JZ EXIT8
	ACALL LCD_WRITE
	INC DPTR
	SJMP LOOP8
	ACALL DELAY	
EXIT8:
	ACALL LINE2				
	LJMP KEYPAD1			// GOI TOI BAN PHIM DE NHAP MAT KHAU
	
CHECK_RIGHT:					// HAM HIEN THI NHAP MAT KHAU DUNG
	ACALL CLEAR_SCREEN
	MOV DPTR, #THANHCONG
	ACALL DELAY
LOOP6:
		MOV A, #00H
		MOVC A,@A+DPTR
		JZ EXIT2
		ACALL LCD_WRITE
		INC DPTR
		SJMP LOOP6
		ACALL DELAY
			
EXIT2: 

MOTOR: 				// HAM MOTOR
	SETB P3.6			// DAT CHAN P3.6 O MUC CAO
	CLR P3.7			// DAT CHAN P3.7 O MUC THAP

	

LCD_INIT:				// HAM KHOI DONG MAN HINH LCD
	CLR RS				// DAT CHAN RS O MUC THAP
	CLR RW				// DAT CHAN RW O MUC THAP
	SETB E				// DAT CHAN E O MUC CAO
	ACALL LCD_COMMAND
	ACALL DELAY
	MOV A, #38H 			// SU DUNG 2 HANG VA MA TRAN 5X7
	ACALL LCD_COMMAND
	MOV A, #0EH				// MAN HINH BAT CON TRO NHAP NHAY TAT
	ACALL LCD_COMMAND
	MOV A, #80H				
	ACALL LCD_COMMAND
	MOV A, #0CH 			// BAT MAN HINH HIEN THI, TAT CON TRO
	ACALL LCD_COMMAND
	RET
LCD_COMMAND:
	CLR RS				// DAT CHAN RS O MUC THAP ( GUI MOT LENH DEN MAN HINH LCD)
	CLR RW				// DAT CHAN RW O MUC THAP  ( GHI DU LIEU VAO MAN HINH LCD)
	ACALL DELAY
	MOV DULIEU, A		// DI CHUYEN GIA TRI TRONG THANH GHI A VAO BIEN DU LIEU
	SETB E				// DAT CHAN E O MUC CAO ( CHO PHEP MAN HINH LCD NHAN DU LIEU)
	CLR RS
	CLR E
	RET


LCD_STRING:			// HAM 
	MOV A, #0			// DI CHUYEN GIA TRI 0 VAO THANH GHI A
	MOVC A, @A+DPTR		// CHUYEN MOT BYTE DU LIEU TU VUNG NHO TRONG THANH GHI DPTR CONG VS GIA TRI TRONG THI GHI A VAO THANH GHI A
	JZ AGAIN			// KIEM TRA GIA TRI TRONG THANH GHI A, NEU BANG 0 THI NHAY TOI AGAIN
	ACALL LCD_WRITE
	ACALL DELAY
AGAIN:
	RET

LCD_WRITE:			// HAM HIEN THI CHU RA MAN HINH LCD
	SETB RS			// DAT CHAN RS O MUC CAO
	CLR RW			// DAT CHAN RW O MUC THAP
	MOV DULIEU, A
	ACALL DELAY
	SETB E			// DAT CHAN E O MUC CAO
	CLR E
	RET

LINE2:			// HIEN THI CHU O DONG 2 CUA MAN HINH LCD
	MOV A, #0C0H
	ACALL LCD_COMMAND
	//ACALL LCD_WRITE
	ACALL DELAY10MS
	RET
	// CAC HAM DELAY SU DUNG TIMER
DELAY: 			
	MOV TMOD,#01H
	SETB TR0
	JNB TF0,$
	CLR TR0
	CLR TF0
	RET

DELAY10MS:
	MOV TMOD,#01H
	MOV TH0, #00H
	MOV TL0, #00H
	SETB TR0
HERE:
	JNB TF0,HERE
	CLR TR0
	CLR TF0
RET


DELAY_0_1S:
	MOV 52H,#200
	L1: MOV 53H,#250
	L2:  MOV 54H,#2
	DJNZ 54H,$
	DJNZ 53H,L2
	DJNZ 52H,L1
RET

DELAY50S:
	MOV R4, #1000
LOOP_DELAY:
		MOV TMOD, #10H 			// BAT TIMER 1 16 BIT
		MOV TH1, #3CH
		MOV TL1, #0B0H
		SETB TR1				//  
		JNB TF1, $		// NHAY TAI CHO
		CLR TR1     // NEU TIMER TRAN THI DUNG TIMER
		CLR TF1     // XOA CO TRAN
		DJNZ R4, LOOP_DELAY
	RET	

CLEAR_SCREEN:		// HAM XOA TOAN BO MAN HINH
	MOV A, #0X01
	ACALL LCD_COMMAND
	ACALL DELAY
	RET
	
THONGTIN1: DB 'NHAP MAT KHAU : ',00H
THONGTIN2: DB 'DOI MAT KHAU X', 00H
NHAP_PASS: DB 'HAY NHAP PASS: ', 00H 
THANHCONG: DB 'MAT KHAU DUNG', 00H
THATBAI: DB 'MAT KHAU SAI', 00H
SAI: DB 'KHONG DUNG', 00H
NHAP_PASS_CU:  DB 'MAT KHAU CU:', 00H
PASS_MOI: DB 'MAT KHAU MOI:', 00H
NHAP_LAI: DB 'NHAP LAI MK:', 00H
SAVE_SUCCESS: DB 'LUU THANH CONG', 00H
CHO50S: DB 'KHOA 50S', 00H
	


END

	
	
	